service:
  name: tweaks-storage-api
  useDotenv: true

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup

custom:
  #   # Enable warmup on all functions (only for production and staging)
  warmup:
    enabled: true

provider:
  name: aws
  runtime: nodejs12.20

package:
  individually: true
  include:
    - .env

functions:
  main: # The name of the lambda function
    handler: src/lambda.handler # The module 'handler' is exported in the file './lambda'
    events:
      - http:
          method: any
          path: /{any+}